export const FETCHING_CONVO_REQUEST = 'FETCHING_CONVO_REQUEST';
export const FETCHING_CONVO_SUCCESS = 'FETCHING_CONVO_SUCCESS';
export const FETCHING_CONVO_FAILURE = 'FETCHING_CONVO_FAILURE';
export const ADD_SELECTED_USER = 'ADD-SELECTED-USER';

